### ISSUE TITLE
Low Performance Mode and High Performance Mode Incorrectly Labeled?

### ISSUE THREAD

**Issue by pythonmcpi** [boredomgames/GeoBounce#1]
The comments for low and high performance mode:
```
# low
#SPEED = 10
#GRAVITY = 30

# high
#SPEED = 5
#GRAVITY = 15
```

Are the comment labels switched? Because it seems to be so.

**Comment by HereIsKevin** [comment]
They're not. The high performance mode has more frames, so it can execute more in the same amount of time. Low performance is 30 fps, high is 60 fps. Therefore, the speed is halved for the high performance mode
